/* The following code was generated by JFlex 1.4.3 on 9/12/12 6:31 PM */

package compiler.logl;

import java_cup.runtime.Symbol;
import javax.swing.JTextArea;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/12/12 6:31 PM from the specification file
 * <tt>l_scanner.jflex</tt>
 */
public class L_Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\2\0\1\2\22\0\1\3\1\30\1\12\1\27"+
    "\1\35\1\0\1\36\1\11\1\47\1\50\1\26\1\42\1\53\1\7"+
    "\1\10\1\25\12\5\1\0\1\24\1\46\1\44\1\45\2\0\32\4"+
    "\3\0\1\43\1\6\1\0\1\17\1\4\1\33\1\16\1\14\1\21"+
    "\2\4\1\31\2\4\1\22\1\41\1\32\1\20\1\40\1\4\1\15"+
    "\1\23\1\37\1\34\1\13\4\4\1\51\1\0\1\52\uff7f\0\1\4"+
    "\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\1\6"+
    "\2\1\7\3\1\7\1\10\1\11\2\1\2\3\2\1"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\4\0\1\24\4\3\1\25\2\3\1\0"+
    "\2\26\2\0\1\27\1\30\1\3\1\31\1\0\1\32"+
    "\1\0\1\33\1\34\1\35\1\36\1\0\1\37\3\3"+
    "\1\40\2\3\2\0\1\41\1\3\1\42\3\3\1\43"+
    "\1\0\2\3\1\44\1\3\1\45\1\0\1\3\1\46"+
    "\1\3\1\0\2\3\1\0\1\3\1\0\1\3\1\47"+
    "\2\3\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\130\0\204\0\260\0\334\0\u0108"+
    "\0\54\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c"+
    "\0\u0268\0\u0294\0\u02c0\0\u02ec\0\54\0\u0318\0\u0344\0\u0370"+
    "\0\u039c\0\u03c8\0\u03f4\0\54\0\54\0\u0420\0\u044c\0\u0478"+
    "\0\54\0\54\0\54\0\54\0\54\0\u04a4\0\334\0\u04d0"+
    "\0\u0160\0\54\0\u04fc\0\u0528\0\u0554\0\u0580\0\204\0\u05ac"+
    "\0\u05d8\0\u02c0\0\54\0\u0604\0\u0630\0\u065c\0\54\0\204"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\54\0\54\0\54"+
    "\0\u0764\0\u0764\0\54\0\u0790\0\u07bc\0\u07e8\0\204\0\u0814"+
    "\0\u0840\0\u086c\0\u0898\0\204\0\u08c4\0\u08f0\0\u091c\0\u0948"+
    "\0\u0974\0\204\0\u09a0\0\u09cc\0\u09f8\0\204\0\u0a24\0\204"+
    "\0\u0a50\0\u0a7c\0\204\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58"+
    "\0\u0b84\0\u0bb0\0\u0bdc\0\54\0\u0c08\0\u0c34\0\204";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\5\1\16\1\17"+
    "\1\20\1\21\1\5\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\2\5\1\32\1\33\3\5\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\55\0\1\3\56\0\3\5\4\0\11\5\5\0"+
    "\4\5\2\0\3\5\17\0\1\6\2\0\1\46\47\0"+
    "\2\5\1\47\4\0\11\5\5\0\4\5\2\0\3\5"+
    "\17\0\1\6\46\0\54\50\12\51\1\52\41\51\4\0"+
    "\3\5\4\0\1\5\1\53\7\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\7\5\1\54\1\5\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\1\5\1\55"+
    "\7\5\5\0\4\5\2\0\3\5\16\0\3\5\4\0"+
    "\11\5\5\0\1\5\1\56\2\5\2\0\3\5\16\0"+
    "\3\5\4\0\2\5\1\57\6\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\4\5\1\60\4\5\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\1\5\1\61"+
    "\7\5\5\0\4\5\2\0\3\5\12\0\1\62\1\63"+
    "\1\64\51\62\26\0\1\65\55\0\1\66\67\0\1\67"+
    "\13\0\3\5\4\0\6\5\1\70\2\5\5\0\4\5"+
    "\2\0\3\5\16\0\3\5\4\0\5\5\1\71\3\5"+
    "\5\0\4\5\2\0\3\5\16\0\1\72\1\0\1\73"+
    "\4\0\11\72\5\0\4\72\2\0\3\72\16\0\1\74"+
    "\1\0\1\75\4\0\11\74\5\0\4\74\2\0\3\74"+
    "\56\0\1\76\53\0\1\77\53\0\1\100\14\0\1\101"+
    "\1\0\1\102\55\0\1\103\46\0\3\5\4\0\2\5"+
    "\1\104\6\5\5\0\4\5\2\0\3\5\16\0\3\5"+
    "\4\0\10\5\1\105\5\0\4\5\2\0\3\5\16\0"+
    "\3\5\4\0\6\5\1\106\2\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\3\5\1\107\5\5\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\7\5\1\110"+
    "\1\5\5\0\4\5\2\0\3\5\16\0\3\5\4\0"+
    "\11\5\5\0\4\5\2\0\1\111\2\5\13\0\1\63"+
    "\52\0\26\65\1\112\25\65\31\0\1\113\26\0\3\5"+
    "\4\0\11\5\5\0\4\5\2\0\1\114\2\5\16\0"+
    "\3\72\4\0\11\72\5\0\4\72\2\0\3\72\16\0"+
    "\2\72\1\73\4\0\11\72\5\0\4\72\2\0\3\72"+
    "\16\0\3\74\4\0\11\74\5\0\4\74\2\0\3\74"+
    "\16\0\2\74\1\75\4\0\11\74\5\0\4\74\2\0"+
    "\3\74\17\0\1\101\52\0\3\5\4\0\3\5\1\115"+
    "\5\5\5\0\4\5\2\0\3\5\16\0\3\5\4\0"+
    "\1\5\1\116\7\5\5\0\4\5\2\0\3\5\16\0"+
    "\3\5\4\0\11\5\5\0\3\5\1\117\2\0\1\5"+
    "\1\120\1\5\16\0\3\5\4\0\10\5\1\121\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\6\5\1\122"+
    "\2\5\5\0\4\5\2\0\3\5\12\0\25\65\1\63"+
    "\1\112\25\65\32\0\1\123\25\0\3\5\4\0\4\5"+
    "\1\124\4\5\5\0\4\5\2\0\3\5\16\0\3\5"+
    "\4\0\11\5\5\0\1\125\3\5\2\0\3\5\16\0"+
    "\3\5\4\0\11\5\5\0\1\5\1\126\2\5\2\0"+
    "\3\5\16\0\3\5\4\0\4\5\1\127\4\5\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\5\5\1\130"+
    "\3\5\5\0\4\5\2\0\3\5\45\0\1\131\24\0"+
    "\3\5\4\0\3\5\1\132\5\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\6\5\1\133\2\5\5\0"+
    "\4\5\2\0\3\5\16\0\3\5\4\0\2\5\1\134"+
    "\6\5\5\0\4\5\2\0\3\5\34\0\1\135\35\0"+
    "\3\5\4\0\1\5\1\136\7\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\4\5\1\137\4\5\5\0"+
    "\4\5\2\0\3\5\46\0\1\140\23\0\3\5\4\0"+
    "\2\5\1\121\6\5\5\0\4\5\2\0\3\5\16\0"+
    "\3\5\4\0\11\5\5\0\4\5\2\0\2\5\1\141"+
    "\30\0\1\142\41\0\3\5\4\0\1\5\1\143\7\5"+
    "\5\0\4\5\2\0\3\5\26\0\1\144\43\0\3\5"+
    "\4\0\11\5\5\0\4\5\2\0\1\145\2\5\16\0"+
    "\3\5\4\0\1\5\1\146\7\5\5\0\4\5\2\0"+
    "\3\5\16\0\3\5\4\0\2\5\1\147\6\5\5\0"+
    "\4\5\2\0\3\5\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3168];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\1\11\13\1\1\11\6\1\2\11"+
    "\3\1\5\11\4\0\1\11\7\1\1\0\1\11\1\1"+
    "\2\0\1\11\3\1\1\0\1\1\1\0\3\11\1\1"+
    "\1\0\1\11\6\1\2\0\7\1\1\0\5\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\1\1\0\1\1\1\11"+
    "\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	/*************************
	 * Console
	 *************************/
	JTextArea console	=	new JTextArea();
	public void setconsole(JTextArea console){
		this.console=console;
	}
	public JTextArea getConsole(){
		return this.console;
	}
	/*************************
	 * Symbols
	 *************************/
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public L_Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public L_Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 122) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return symbol(L_Sym.LLAVE1,yytext());
          }
        case 41: break;
        case 26: 
          { return symbol(L_Sym.CALL,yytext());
          }
        case 42: break;
        case 3: 
          { return symbol(L_Sym.ID,yytext());
          }
        case 43: break;
        case 39: 
          { return symbol(L_Sym.RW_INCLUDE,yytext());
          }
        case 44: break;
        case 10: 
          { return symbol(L_Sym.PLUS,yytext());
          }
        case 45: break;
        case 8: 
          { return symbol(L_Sym.DIV,yytext());
          }
        case 46: break;
        case 11: 
          { return symbol(L_Sym.EXP,yytext());
          }
        case 47: break;
        case 13: 
          { return symbol(L_Sym.MAYORQ,yytext());
          }
        case 48: break;
        case 16: 
          { return symbol(L_Sym.PAR2,yytext());
          }
        case 49: break;
        case 4: 
          { return symbol(L_Sym.INT,yytext());
          }
        case 50: break;
        case 1: 
          { console.append("[Error] Illegal character <"+yytext()+"> at line "+(yyline+1)+" column " +(yycolumn+1)+"\n");
          }
        case 51: break;
        case 6: 
          { return symbol(L_Sym.DOT,yytext());
          }
        case 52: break;
        case 14: 
          { return symbol(L_Sym.MENORQ,yytext());
          }
        case 53: break;
        case 40: 
          { return symbol(L_Sym.RW_DEFPARAMETER,yytext());
          }
        case 54: break;
        case 28: 
          { return symbol(L_Sym.MAYOR_EQUALQ,yytext());
          }
        case 55: break;
        case 20: 
          { return symbol(L_Sym.STRING,yytext());
          }
        case 56: break;
        case 24: 
          { return symbol(L_Sym.RW_IF,yytext());
          }
        case 57: break;
        case 25: 
          { return symbol(L_Sym.VAR,yytext());
          }
        case 58: break;
        case 29: 
          { return symbol(L_Sym.MENOR_EQUALQ,yytext());
          }
        case 59: break;
        case 12: 
          { return symbol(L_Sym.EQUAL,yytext());
          }
        case 60: break;
        case 7: 
          { return symbol(L_Sym.SEMIC,yytext());
          }
        case 61: break;
        case 18: 
          { return symbol(L_Sym.LLAVE2,yytext());
          }
        case 62: break;
        case 33: 
          { return symbol(L_Sym.NOT,yytext());
          }
        case 63: break;
        case 2: 
          { /*nada*/
          }
        case 64: break;
        case 35: 
          { return symbol(L_Sym.RW_SETF,yytext());
          }
        case 65: break;
        case 37: 
          { return symbol(L_Sym.BOOLEAN,yytext());
          }
        case 66: break;
        case 15: 
          { return symbol(L_Sym.PAR1,yytext());
          }
        case 67: break;
        case 31: 
          { return symbol(L_Sym.CHAR,yytext());
          }
        case 68: break;
        case 23: 
          { return symbol(L_Sym.NEQUAL,yytext());
          }
        case 69: break;
        case 5: 
          { return symbol(L_Sym.SUB,yytext());
          }
        case 70: break;
        case 22: 
          { /*COMENTARIO*/
          }
        case 71: break;
        case 19: 
          { return symbol(L_Sym.COLON,yytext());
          }
        case 72: break;
        case 9: 
          { return symbol(L_Sym.MUL,yytext());
          }
        case 73: break;
        case 32: 
          { return symbol(L_Sym.AND,yytext());
          }
        case 74: break;
        case 27: 
          { return symbol(L_Sym.DEQUAL,yytext());
          }
        case 75: break;
        case 21: 
          { return symbol(L_Sym.OR,yytext());
          }
        case 76: break;
        case 36: 
          { return symbol(L_Sym.RW_DEFUN,yytext());
          }
        case 77: break;
        case 38: 
          { return symbol(L_Sym.RW_ELSEIF,yytext());
          }
        case 78: break;
        case 30: 
          { return symbol(L_Sym.DOUBLE,yytext());
          }
        case 79: break;
        case 34: 
          { return symbol(L_Sym.RW_ELSE,yytext());
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(L_Sym.EOF,yytext());
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
