
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 12 11:33:05 CST 2012
//----------------------------------------------------

package compiler.logp;

/** CUP generated class containing symbol constants. */
public class P_Sym {
  /* terminals */
  public static final int PAR2 = 9;
  public static final int PAR1 = 8;
  public static final int RW_INCLUDE = 4;
  public static final int CHAR = 31;
  public static final int LLAVE2 = 11;
  public static final int LLAVE1 = 10;
  public static final int MENORQ = 23;
  public static final int SEMIC = 6;
  public static final int DOUBLE = 14;
  public static final int INT = 2;
  public static final int MENOR_EQUALQ = 25;
  public static final int RW_ELSEIF = 35;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int OR = 18;
  public static final int CALL = 32;
  public static final int DIV = 28;
  public static final int PLUS = 27;
  public static final int EXP = 30;
  public static final int DOT = 13;
  public static final int ID = 3;
  public static final int RW_SUB = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int EQUAL = 7;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int DEQUAL = 21;
  public static final int COLON = 33;
  public static final int RW_IF = 34;
  public static final int MAYORQ = 22;
  public static final int NEQUAL = 20;
  public static final int MAYOR_EQUALQ = 24;
  public static final int RW_ELSE = 36;
  public static final int STRING = 15;
  public static final int SUB = 26;
  public static final int VAR = 5;
}

