/* The following code was generated by JFlex 1.4.3 on 9/25/12 11:06 AM */

package compiler.logc;


import java_cup.runtime.Symbol;
import javax.swing.JTextArea;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import java.awt.Color;

import compiler.CeParseUtils;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/25/12 11:06 AM from the specification file
 * <tt>c_scanner.jflex</tt>
 */
public class C_Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\2\0\1\2\22\0\1\3\1\27\1\12\1\26"+
    "\2\0\1\42\1\11\1\51\1\52\1\25\1\45\1\56\1\7\1\10"+
    "\1\24\12\5\1\0\1\55\1\50\1\47\1\44\2\0\32\4\3\0"+
    "\1\46\1\6\1\0\1\17\1\35\1\32\1\16\1\14\1\21\1\36"+
    "\1\37\1\30\1\4\1\41\1\22\1\4\1\31\1\20\2\4\1\15"+
    "\1\23\1\34\1\33\1\13\1\40\3\4\1\53\1\43\1\54\123\0"+
    "\1\4\37\0\1\4\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\1\6"+
    "\2\1\6\3\1\7\1\10\1\1\1\11\4\3\2\1"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\2\0\1\25\2\0\1\26\10\3"+
    "\3\0\1\27\1\30\5\3\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\0\1\37\6\3\1\40\1\3\2\41"+
    "\2\0\1\42\5\3\1\43\1\44\5\3\1\45\1\0"+
    "\1\46\6\3\1\47\2\3\1\0\1\50\1\3\1\51"+
    "\1\3\1\52\1\53\1\54\1\55\1\0\2\3\1\0"+
    "\1\56\4\0\2\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\57\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\57\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0468\0\57\0\57\0\u0497\0\u04c6"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\u04f5\0\353"+
    "\0\57\0\u0524\0\u0178\0\57\0\u0553\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\57"+
    "\0\215\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\57\0\57"+
    "\0\57\0\57\0\57\0\u0843\0\u0843\0\57\0\u0872\0\u08a1"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\215\0\u098c\0\57\0\u09bb"+
    "\0\u09ea\0\u0a19\0\215\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04"+
    "\0\215\0\215\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\57"+
    "\0\u0c1e\0\215\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38"+
    "\0\215\0\u0d67\0\u0d96\0\u0dc5\0\215\0\u0df4\0\215\0\u0e23"+
    "\0\215\0\215\0\215\0\215\0\u0e52\0\u0e81\0\u0eb0\0\u0edf"+
    "\0\215\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\57\0\u0fca";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\2\5"+
    "\1\20\1\5\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\5\1\27\2\5\1\30\2\5\1\31\1\5\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\60\0\1\3\61\0\3\5"+
    "\4\0\11\5\4\0\12\5\22\0\1\6\2\0\1\47"+
    "\52\0\2\5\1\50\4\0\11\5\4\0\12\5\22\0"+
    "\1\6\36\0\1\51\12\0\57\52\12\53\1\54\44\53"+
    "\4\0\3\5\4\0\1\5\1\55\3\5\1\56\3\5"+
    "\4\0\12\5\21\0\3\5\4\0\7\5\1\57\1\5"+
    "\4\0\12\5\21\0\3\5\4\0\1\5\1\60\7\5"+
    "\4\0\12\5\21\0\3\5\4\0\5\5\1\61\3\5"+
    "\4\0\12\5\21\0\3\5\4\0\4\5\1\62\1\63"+
    "\3\5\4\0\12\5\21\0\3\5\4\0\11\5\4\0"+
    "\4\5\1\64\5\5\41\0\1\65\1\66\60\0\1\67"+
    "\76\0\1\70\13\0\3\5\4\0\6\5\1\71\2\5"+
    "\4\0\1\5\1\72\10\5\21\0\3\5\4\0\11\5"+
    "\4\0\7\5\1\73\2\5\21\0\3\5\4\0\2\5"+
    "\1\74\2\5\1\75\3\5\4\0\12\5\21\0\3\5"+
    "\4\0\11\5\4\0\7\5\1\76\2\5\57\0\1\77"+
    "\57\0\1\100\62\0\1\101\56\0\1\102\56\0\1\103"+
    "\14\0\1\104\1\0\1\105\60\0\1\106\51\0\3\5"+
    "\4\0\2\5\1\107\6\5\4\0\12\5\21\0\3\5"+
    "\4\0\11\5\4\0\1\110\11\5\21\0\3\5\4\0"+
    "\10\5\1\111\4\0\12\5\21\0\3\5\4\0\11\5"+
    "\4\0\4\5\1\112\5\5\21\0\3\5\4\0\11\5"+
    "\4\0\3\5\1\113\6\5\21\0\3\5\4\0\7\5"+
    "\1\114\1\5\4\0\12\5\21\0\3\5\4\0\2\5"+
    "\1\115\6\5\4\0\12\5\21\0\3\5\4\0\2\5"+
    "\1\116\6\5\4\0\12\5\15\0\1\65\1\117\1\120"+
    "\54\65\25\66\1\121\31\66\30\0\1\122\32\0\3\5"+
    "\4\0\11\5\4\0\4\5\1\123\5\5\21\0\3\5"+
    "\4\0\4\5\1\124\4\5\4\0\12\5\21\0\3\5"+
    "\4\0\1\5\1\125\7\5\4\0\12\5\21\0\3\5"+
    "\4\0\5\5\1\126\3\5\4\0\12\5\21\0\3\5"+
    "\4\0\11\5\4\0\1\127\11\5\22\0\1\104\55\0"+
    "\3\5\4\0\3\5\1\130\5\5\4\0\12\5\21\0"+
    "\3\5\4\0\3\5\1\131\5\5\4\0\12\5\21\0"+
    "\3\5\4\0\1\5\1\132\7\5\4\0\12\5\21\0"+
    "\3\5\4\0\11\5\4\0\3\5\1\133\6\5\21\0"+
    "\3\5\4\0\11\5\4\0\5\5\1\134\4\5\21\0"+
    "\3\5\4\0\10\5\1\135\4\0\12\5\21\0\3\5"+
    "\4\0\11\5\4\0\1\136\2\5\1\137\6\5\16\0"+
    "\1\117\55\0\24\66\1\140\1\121\31\66\31\0\1\141"+
    "\31\0\3\5\4\0\2\5\1\142\6\5\4\0\12\5"+
    "\21\0\3\5\4\0\4\5\1\143\4\5\4\0\12\5"+
    "\21\0\3\5\4\0\7\5\1\144\1\5\4\0\12\5"+
    "\21\0\3\5\4\0\7\5\1\145\1\5\4\0\12\5"+
    "\21\0\3\5\4\0\4\5\1\146\4\5\4\0\12\5"+
    "\21\0\3\5\4\0\2\5\1\147\6\5\4\0\12\5"+
    "\21\0\3\5\4\0\7\5\1\150\1\5\4\0\12\5"+
    "\21\0\3\5\4\0\5\5\1\151\3\5\4\0\12\5"+
    "\21\0\3\5\4\0\11\5\4\0\1\5\1\152\10\5"+
    "\21\0\3\5\4\0\11\5\4\0\2\5\1\153\7\5"+
    "\47\0\1\154\30\0\3\5\4\0\11\5\4\0\11\5"+
    "\1\155\21\0\3\5\4\0\1\5\1\156\7\5\4\0"+
    "\12\5\21\0\3\5\4\0\1\5\1\157\7\5\4\0"+
    "\12\5\21\0\3\5\4\0\3\5\1\160\5\5\4\0"+
    "\12\5\21\0\3\5\4\0\11\5\4\0\1\5\1\161"+
    "\10\5\21\0\3\5\4\0\1\5\1\162\7\5\4\0"+
    "\12\5\21\0\3\5\4\0\11\5\4\0\6\5\1\163"+
    "\3\5\21\0\3\5\4\0\11\5\4\0\4\5\1\164"+
    "\5\5\37\0\1\165\40\0\3\5\4\0\4\5\1\166"+
    "\4\5\4\0\12\5\21\0\3\5\4\0\1\5\1\167"+
    "\7\5\4\0\12\5\50\0\1\170\27\0\3\5\4\0"+
    "\11\5\4\0\1\5\1\171\10\5\21\0\3\5\4\0"+
    "\2\5\1\135\6\5\4\0\12\5\33\0\1\172\54\0"+
    "\1\173\43\0\3\174\53\0\1\175\3\174\54\175\1\176"+
    "\1\177\1\0\53\175\1\0\1\176\55\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4089];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\1\11\11\1\1\11\11\1\2\11"+
    "\2\1\6\11\2\0\1\11\2\0\1\11\10\1\3\0"+
    "\1\11\6\1\5\11\1\1\1\0\1\11\10\1\1\11"+
    "\1\1\2\0\15\1\1\11\1\0\12\1\1\0\10\1"+
    "\1\0\2\1\1\0\1\1\4\0\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	/*************************
	 * Utils
	 *************************/
	CeParseUtils utils;
	
	public void setUtils(CeParseUtils utils){
		this.utils=utils;
		this.doc=utils.getDocument();
	}
	/*************************
	 * Styled document
	 *************************/
	 DefaultStyledDocument 	doc;
	/*************************
	 * Console
	 *************************/
	public void print(String text){
		this.utils.getConsole().print(text);
	}
	public void println(String text){
		this.utils.getConsole().println(text);
	}
	/*************************
	 * Symbols
	 *************************/
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
		addFormat(Color.black,false,false,false);
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type, Object value, Color color) {
		addFormat(color,false,false,false);
        return new Symbol(type, yyline, yycolumn, value);
    }
    private void addFormat(Color color,boolean bold,boolean italic,boolean underline){
		if(doc==null){
			return;
		}
		SimpleAttributeSet 	sas	= new SimpleAttributeSet();
		
		//StyleConstants.setFontSize(sas, 22);
		StyleConstants.setForeground(sas, color);
		StyleConstants.setBold(sas, bold);
		StyleConstants.setItalic(sas, italic);
		StyleConstants.setUnderline(sas, underline);
		
		doc.setCharacterAttributes(yychar, yylength(), sas, false);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public C_Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public C_Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return symbol(C_Sym.SEMIC,yytext());
          }
        case 48: break;
        case 35: 
          { return symbol(C_Sym.KW_VOID,yytext(),Color.blue);
          }
        case 49: break;
        case 13: 
          { return symbol(C_Sym.EQ,yytext());
          }
        case 50: break;
        case 20: 
          { return symbol(C_Sym.COMA,yytext());
          }
        case 51: break;
        case 10: 
          { return symbol(C_Sym.MAYORQ,yytext());
          }
        case 52: break;
        case 7: 
          { return symbol(C_Sym.DIV,yytext());
          }
        case 53: break;
        case 12: 
          { return symbol(C_Sym.EXP,yytext());
          }
        case 54: break;
        case 11: 
          { return symbol(C_Sym.PLUS,yytext());
          }
        case 55: break;
        case 33: 
          { /*COMENTARIO*/addFormat(Color.gray,false,true,false);
          }
        case 56: break;
        case 14: 
          { return symbol(C_Sym.MENORQ,yytext());
          }
        case 57: break;
        case 36: 
          { return symbol(C_Sym.KW_ELSE,yytext(),Color.red);
          }
        case 58: break;
        case 16: 
          { return symbol(C_Sym.PAR2,yytext());
          }
        case 59: break;
        case 27: 
          { return symbol(C_Sym.MAYOR_EQQ,yytext());
          }
        case 60: break;
        case 22: 
          { return symbol(C_Sym.STRING,yytext(),Color.orange);
          }
        case 61: break;
        case 21: 
          { return symbol(C_Sym.ARROW,yytext());
          }
        case 62: break;
        case 6: 
          { return symbol(C_Sym.DOT,yytext());
          }
        case 63: break;
        case 38: 
          { return symbol(C_Sym.KW_CHAR,yytext(),Color.blue);
          }
        case 64: break;
        case 31: 
          { return symbol(C_Sym.CHAR,yytext(),Color.orange);
          }
        case 65: break;
        case 43: 
          { return symbol(C_Sym.KW_DOUBLE,yytext(),Color.blue);
          }
        case 66: break;
        case 1: 
          { addFormat(Color.red,false,false,true);
			println("[Error] Illegal character <"+yytext()+"> at line "+(yyline+1)+" column " +(yycolumn+1));
          }
        case 67: break;
        case 41: 
          { return symbol(C_Sym.KW_WHILE,yytext(),Color.red);
          }
        case 68: break;
        case 39: 
          { return symbol(C_Sym.BOOLEAN,yytext(),Color.blue);
          }
        case 69: break;
        case 40: 
          { return symbol(C_Sym.KW_BREAK,yytext(),Color.red);
          }
        case 70: break;
        case 18: 
          { return symbol(C_Sym.LLAVE2,yytext());
          }
        case 71: break;
        case 30: 
          { return symbol(C_Sym.DOUBLE,yytext(),Color.green);
          }
        case 72: break;
        case 9: 
          { return symbol(C_Sym.NOT,yytext());
          }
        case 73: break;
        case 46: 
          { return symbol(C_Sym.KW_BOOLEAN,yytext(),Color.blue);
          }
        case 74: break;
        case 26: 
          { return symbol(C_Sym.OR,yytext());
          }
        case 75: break;
        case 42: 
          { return symbol(C_Sym.KW_RETURN,yytext(),Color.red);
          }
        case 76: break;
        case 24: 
          { return symbol(C_Sym.KW_IF,yytext(),Color.red);
          }
        case 77: break;
        case 32: 
          { return symbol(C_Sym.KW_FOR,yytext(),Color.red);
          }
        case 78: break;
        case 4: 
          { return symbol(C_Sym.INT,yytext(),Color.green);
          }
        case 79: break;
        case 34: 
          { return symbol(C_Sym.KW_INT,yytext(),Color.blue);
          }
        case 80: break;
        case 37: 
          { /*COMENTARIO*/
          }
        case 81: break;
        case 5: 
          { return symbol(C_Sym.SUB,yytext());
          }
        case 82: break;
        case 15: 
          { return symbol(C_Sym.PAR1,yytext());
          }
        case 83: break;
        case 8: 
          { return symbol(C_Sym.MUL,yytext());
          }
        case 84: break;
        case 29: 
          { return symbol(C_Sym.MENOR_EQQ,yytext());
          }
        case 85: break;
        case 44: 
          { return symbol(C_Sym.KW_STRING,yytext(),Color.blue);
          }
        case 86: break;
        case 25: 
          { return symbol(C_Sym.AND,yytext());
          }
        case 87: break;
        case 28: 
          { return symbol(C_Sym.EQEQ,yytext());
          }
        case 88: break;
        case 47: 
          { return symbol(C_Sym.KW_INCLUDE,yytext(),Color.blue);
          }
        case 89: break;
        case 2: 
          { /*nada*/addFormat(Color.black,false,false,false);
          }
        case 90: break;
        case 3: 
          { return symbol(C_Sym.ID,yytext());
          }
        case 91: break;
        case 23: 
          { return symbol(C_Sym.NEQ,yytext());
          }
        case 92: break;
        case 45: 
          { return symbol(C_Sym.KW_STRUCT,yytext(),Color.red);
          }
        case 93: break;
        case 17: 
          { return symbol(C_Sym.LLAVE1,yytext());
          }
        case 94: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(C_Sym.EOF,yytext());
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
