
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 27 09:21:54 CST 2012
//----------------------------------------------------

package compiler.logc;

/** CUP generated class containing symbol constants. */
public class C_Sym {
  /* terminals */
  public static final int PAR2 = 26;
  public static final int PAR1 = 25;
  public static final int CHAR = 6;
  public static final int KW_INT = 8;
  public static final int LLAVE2 = 28;
  public static final int LLAVE1 = 27;
  public static final int MENORQ = 20;
  public static final int KW_FOR = 39;
  public static final int MAYOR_EQQ = 21;
  public static final int SEMIC = 13;
  public static final int DOUBLE = 4;
  public static final int KW_DOUBLE = 9;
  public static final int KW_CHAR = 11;
  public static final int INT = 3;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int OR = 30;
  public static final int DIV = 34;
  public static final int PLUS = 32;
  public static final int EXP = 36;
  public static final int MENOR_EQQ = 22;
  public static final int DOT = 15;
  public static final int ID = 2;
  public static final int KW_RETURN = 44;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int COMA = 14;
  public static final int KW_BOOLEAN = 12;
  public static final int EQEQ = 17;
  public static final int NEQ = 18;
  public static final int KW_INCLUDE = 37;
  public static final int EQ = 16;
  public static final int KW_IF = 23;
  public static final int ARROW = 43;
  public static final int KW_VOID = 38;
  public static final int KW_BREAK = 42;
  public static final int MAYORQ = 19;
  public static final int KW_ELSE = 24;
  public static final int KW_STRING = 10;
  public static final int STRING = 5;
  public static final int KW_WHILE = 40;
  public static final int KW_STRUCT = 41;
  public static final int SUB = 33;
}

